# Generated by Django 6.0a1 on 2025-10-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_color_cars_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
    ]
